---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    # Apache Configuration
    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'php-curl', 'php-sqlite3', 'libapache2-mod-php', 'rabbitmq-server', 'php-amqplib' ]

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Set up Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

    # PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "files/info.php.j2"
        dest: "/var/www/{{ http_host }}/info.php"

    - name: Copy PHP Files
      copy:
        src: "{{ playbook_dir }}/lib"
        dest: "/var/www/{{ http_host }}/timmy"
        owner: www-data
        group: www-data
        mode: 0775
    - name: Copy PHP Files
      copy:
        src: "{{ playbook_dir }}/bullshitcard.php"
        dest: "/var/www/{{ http_host }}/timmy"
    - name: Copy PHP Files
      copy:
        src: "{{ playbook_dir }}/test_webhook.php"
        dest: "/var/www/{{ http_host }}/timmy"
    - name: Copy DB
      copy:
        src: "{{ playbook_dir }}/timmy_empty.db"
        dest: "/var/www/{{ http_host }}/timmy/timmy.db"
        force: no
        owner: www-data
        group: www-data
        mode: 0775
    - name: Config template
      template:
        src: "files/Config.php.j2"
        dest: "/var/www/{{ http_host }}/timmy/lib/Config.php"
    - name: Create log dir
      file:
        path: "{{ log_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: 0775

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart RabbitMQ
      service:
        name: rabbitmq-server
        state: restarted
