---
app_user: "ubuntu"
http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "80"
disable_default: true
ansible_python_interpreter: /usr/bin/python3
webhook_secret: ""
test_mode: false
log_dir: "/var/log/timmy"
hosts: "{{ variable_host | default('web') }}"
